### ISSUE TITLE
Include libsequence code within project?

### ISSUE THREAD

**Issue by jeromekelleher** [molpopgen/pyseq#1]
Would it be possible to include the libsequence code within this repo so that it is built as part of the local compile? Usually this just involves listing the source files in setup.py, and setuptools takes care of the rest. The advantage would be that pylibseq could be installed much more easily without root access and without fiddling with LD_LIBRARY_PATH, etc.

**Comment by molpopgen** [comment]
I take it you mean have libsequence as a git sub-module?  That is possible, but it won't solve any shell parameter issues.  libsequence depends on zlib, and the dev branch further depends on TBB, which I'm using for threading.  Optionally, if htslib is present, then libsequence also compiles a BAM reader tool kit.  While all of those are open-source,  they all have different licenses.

The other issue is that libsequence itself is changing quite a bit at the moment.  I may add a further dependency to the GSL, as I'm currently experimenting with using their character matrix type to refactor the polymorphism table objects in libsequence.

So, that's not a "no", but I'm not sure it solves the issue.  IMO, modifying the shell params is easier:

LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH
CPPFLAGS="-I $HOME/include "$CPPFLAGS

**Comment by jeromekelleher** [comment]
Fair enough; I thought the answer might be "it's complicated", but there's no harm in asking! I'll close the issue.

**Comment by molpopgen** [comment]
Yeah--I'm actually finding this to be a general issue with packaging in Python.  Handling external dependencies is a bit inelegant, IMO.

**Comment by jeromekelleher** [comment]
Check out [bioconda](https://bioconda.github.io/) --- it make packaging up stuff with external dependencies really easy.  There's all sorts of stuff like htslib in there already. Having a Bioconda recipe for libsequence would be pretty cool...

**Comment by molpopgen** [comment]
I'll look into that.  libsequence is already packaged in home-brew, as is fwdpp, another library of mine.    i don't maintain the brew recipes, but I'll see how time-consuming bioconda would be.
