### ISSUE TITLE
How to generate msstats-like output using mspms?

### ISSUE THREAD

**Issue by oushujun** [molpopgen/pyseq#10]
Hi Kevin,

Thanks for developing and maintaining pylibseq. 

I have limited experience in Python and C++ coding, but would like to use the functionality of msstats, which has been marked as archival and not maintained. 

I tried libsequence 1.9.2 + msstats-dev, I could not compile msstats-dev:

> $ sudo make install
CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal-1.15 -I m4
/bin/sh: aclocal-1.15: command not found
make: *** [aclocal.m4] Error 127

I could compile msstat-0.3.5 by specifying the path of libsequence, but I encountered an error when trying to use msstats:

> $ sudo CXXFLAGS=-I/opt/software/libsequence/1.9.2--GCC-4.9.4/include LDFLAGS="$LDFLAGS -L/opt/software/libsequence/1.9.2--GCC-4.9.4/lib" ./configure --prefix /mnt/scratch/osj/msstats
$ sudo make
$ sudo make install
$ ./bin/msstats 
./msstats: error while loading shared libraries: libsequence.so.20: cannot open shared object file: No such file or directory

I also tried msprime + libsequence 1.9.2 + pylibseq, I have them installed using bioconda (BTW, please update the readme page and indicate the bioconda way for installation, which it's much easier! I found this out in a hard way...), then I don't know what to do to get the msstats-like output from ms/msprine results, since I never saw a working version of msstats...

From [#5 in msstats](https://github.com/molpopgen/msstats/issues/5), you mentioned using mspms can generate the similar output of msstats, can you provide more details?

Thanks!
Shujun

**Comment by molpopgen** [comment]
The gist of this is covered in the pylibseq [manual](http://molpopgen.github.io/pylibseq/_build/html/index.html).  See "example workflow".

To connect data from msprime to pylibseq, see `help(libsequence.msprime)`, or search for msprime in the manual.

As for "output similar to msstats", that is up to you.  If you want literally the same output, then print to screen the same stats in the same order with the same headers.  But, it is not clear you always want to do that.  It may be better/more efficient to load data into a pandas.DataFrame object or write it to an sqlite3 database, etc.  That part is up to you, and you have the entire Python world to help you.

**Comment by molpopgen** [comment]
As for updating the README, that will happen when 0.2.1 is release.

**Comment by molpopgen** [comment]
Closing.  0.2.1 has been out for a while.
