### ISSUE TITLE
Fst from VariantMatrix

### ISSUE THREAD

**Issue by agladstein** [molpopgen/pyseq#16]
From the documentation it looks to me like `libsequence.fst.Fst` takes the object `polytable.SimData` as input. Is that correct?
I'm reading in msprime simulations as numpy matrix
```
tree_np_matrix_vmat = variant_matrix.VariantMatrix(tree_np_matrix, pos)
```

So, can `libsequence.fst.Fst` take `variant_matrix.VariantMatrix` or `variant_matrix.VariantMatrix.count_alleles` as input?
Or else, how do I calculate Fst from the `VariantMatrix`?

**Comment by molpopgen** [comment]
You convert your numpy data to the correct format to make a SimData. See molpopgen/libsequence#35

Alternately, since the memory layout is the same as `allel`, use that for Fst in the meanwhile.

This is a consequence of no time to work on libsequence.

**Comment by agladstein** [comment]
Ah... 

I haven't been able to find in the docs how to convert from numpy to create the SimData.

I'm not sure what you mean by "use that or Fst".

**Comment by molpopgen** [comment]
> I haven't been able to find in the docs how to convert from numpy to create the SimData.

"Just do it"--all you need is Python. The input for a VariantMatrix is a matrix of integers with rows as sites.  The input for SimData is a list of strings, where each string is a haplotype. (List of positions is needed for both, of course.)

> 
> I'm not sure what you mean by "use that or Fst".

`s/or/for/`

**Comment by agladstein** [comment]
hahaha ok :D
