### ISSUE TITLE
RuntimeError when position floats are not same length

### ISSUE THREAD

**Issue by stsmall** [molpopgen/pyseq#2]
Hi Kevin,
When I run Windows to make sliding windows for stat calculation, if the float representation of each positions are not all the same length (byte representation?), I get the below error:

w = Windows(sd, window_size = 0.10, step_len = 0.05, starting_pos = 0., ending_pos = 1.0)
Traceback (most recent call last):

  File "<ipython-input-616-a03c3e4327b6>", line 1, in <module>
    w = Windows(sd, window_size = 0.10, step_len = 0.05, starting_pos = 0., ending_pos = 1.0)

  File "libsequence/windows.pyx", line 38, in libsequence.windows.Windows.__cinit__ (libsequence/windows.cpp:1439)

  File "libsequence/windows.pyx", line 9, in libsequence.windows.fill_from_SimData (libsequence/windows.cpp:1036)

RuntimeError: range (beg,end) must be sorted in increasing order

e.g., array([ 0.0043,  0.0076,  0.1395, ...,  0.9915,  0.995 ,  0.9962]), produces the error but 
array([ 0.0043,  0.0076,  0.1395, ...,  0.9915,  0.9950 ,  0.9962]) does not. All other functions except Windows behave as normal, at least no errors. Also it doesnt seem like simDataWindows is a part of windows any longer, at least I continue to get an error that it is not found. In the case it is important, I installed pylibseq from the Anaconda repo and am using Ubuntu 16.04 64

thanks,
scott

**Comment by molpopgen** [comment]
Can you provide a minimal reproducible example?  It would be easiest to debug if there were a few lines of code that generate the error.

Also: Python 2 or Python 3?

**Comment by molpopgen** [comment]
I'll see what I can do about fixing the manual for 0.1.8.  It looks like it was built prior to the release getting finalized.

**Comment by stsmall** [comment]
I think the error was caused by the old version of numpy (or something, I updated all packages), since after updating I no longer receive the error. I should have tried that before bothering you. Sorry :(

**Comment by molpopgen** [comment]
No problem.  Glad it worked itself out.

BTW, 0.1.9 is imminent, once I iron out some documentation wrinkles.

The class names change quite a bit and become identical to the libsequence types they model.
