### ISSUE TITLE
Link to the manual is dead

### ISSUE THREAD

**Issue by pmorrell** [molpopgen/pyseq#25]
The link to the manual at the bottom of the primary pylibseq [page](https://github.com/molpopgen/pylibseq) does not work . It returns a "404 File Not Find" error. A similar link at the bottom of the PyPi [page](https://pypi.org/project/pylibseq/) also does not work.

**Comment by molpopgen** [comment]
This is fixed in the dev branch. 

In the meantime, the main project page redirects to the manual.

The content on PyPi is the same as on GitHub, as the former displays any README from the latter.

**Comment by molpopgen** [comment]
Closing.  0.2.3 fixes this and is up on PyPi now.

**Comment by pmorrell** [comment]
Cool!
